## YAML Template.
---
language: node_js
node_js:
  - 6
env:
- MY_VAR=EverythignIsAwesome
- NODE_ENV=TEST
before_install:
- cd converter
- npm install requirejs
install:
  - npm install
script:
- npm test


